//const $ = require('jquery');
require('angular');
require('angular-jwt');
require('angular-ui-router');
require('angular-material');
require('angular-aria');
require('angular-simple-logger');
require('angular-cookies');
require('angular-sanitize');
require('angular-animate');
require('angular-material/angular-material.scss');
require("font-awesome-webpack");